---
name: CI Rust Build
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "**/*.nix"
      - "Cargo.lock"
      - "Cargo.toml"
      - "flake.lock"
      - "flake.nix"
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{github.token}}
          extra-conf: |
            sandbox = false

      - name: Build and test context via Nix
        run: nix build .#context
